USE [master]
GO

/****** Object:  Database [Cap]    Script Date: 5/2/2015 6:49:14 PM ******/
CREATE DATABASE [Cap]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cap_Data', FILENAME = N'D:\RDSDBDATA\DATA\Cap_Data.mdf' , SIZE = 1785216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Cap_Log', FILENAME = N'D:\RDSDBDATA\DATA\Cap_Log.ldf' , SIZE = 2619392KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [Cap] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cap].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cap] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cap] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cap] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cap] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cap] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cap] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cap] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cap] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cap] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cap] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cap] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cap] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cap] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cap] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cap] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Cap] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cap] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cap] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cap] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cap] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cap] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cap] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cap] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Cap] SET  MULTI_USER 
GO

ALTER DATABASE [Cap] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cap] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cap] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cap] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Cap] SET  READ_WRITE 
GO

